// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ClavierDorDbContext))]
    [Migration("20260411182506_RolesUpdate")]
    partial class RolesUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MeilleurScore")
                        .HasColumnType("int");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("Models.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DeuxiemeOption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PremiereOption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuatrièmeOption")
                        .HasColumnType("longtext");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("TroisiemeOption")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Models.Partie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProgessionAlgo")
                        .HasColumnType("int");

                    b.Property<int>("ProgessionAnglais")
                        .HasColumnType("int");

                    b.Property<int>("ProgessionCultureG")
                        .HasColumnType("int");

                    b.Property<int>("ProgessionLogique")
                        .HasColumnType("int");

                    b.Property<int>("ProgessionMDI")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.HasIndex("RoleId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Indice")
                        .HasColumnType("longtext");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<int>("TypeDeQuestion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Models.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("PartieId")
                        .HasColumnType("int");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<int>("ValeurDuScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartieId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Models.Roles.DeveloppeurBack", b =>
                {
                    b.HasBaseType("Models.Roles.Role");

                    b.HasDiscriminator().HasValue("DeveloppeurBack");
                });

            modelBuilder.Entity("Models.Roles.DeveloppeurFront", b =>
                {
                    b.HasBaseType("Models.Roles.Role");

                    b.HasDiscriminator().HasValue("DeveloppeurFront");
                });

            modelBuilder.Entity("Models.Roles.DeveloppeurMobile", b =>
                {
                    b.HasBaseType("Models.Roles.Role");

                    b.HasDiscriminator().HasValue("DeveloppeurMobile");
                });

            modelBuilder.Entity("Models.Options", b =>
                {
                    b.HasOne("Models.Question", null)
                        .WithOne("OptionsProposees")
                        .HasForeignKey("Models.Options", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Partie", b =>
                {
                    b.HasOne("Models.Joueur", "Joueur")
                        .WithMany()
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.Score", b =>
                {
                    b.HasOne("Models.Partie", null)
                        .WithMany("Scores")
                        .HasForeignKey("PartieId");
                });

            modelBuilder.Entity("Models.Partie", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Models.Question", b =>
                {
                    b.Navigation("OptionsProposees");
                });
#pragma warning restore 612, 618
        }
    }
}
