// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ClavierDorDbContext))]
    [Migration("20260213233659_UpdatedBd")]
    partial class UpdatedBd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeilleurScore")
                        .HasColumnType("int");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("Models.Options", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeuxiemeOption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PremiereOption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuatrièmeOption")
                        .HasColumnType("longtext");

                    b.Property<string>("TroisiemeOption")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Models.Partie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JoueurId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Indice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OptionsProposeesId")
                        .HasColumnType("int");

                    b.Property<string>("Reponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptionsProposeesId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Models.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasDiscriminator().HasValue("Role");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PartieId")
                        .HasColumnType("int");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<int>("ValeurDuScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartieId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Models.Roles.DeveloppeurBack", b =>
                {
                    b.HasBaseType("Models.Roles.Role");

                    b.HasDiscriminator().HasValue("DeveloppeurBack");
                });

            modelBuilder.Entity("Models.Roles.DeveloppeurFront", b =>
                {
                    b.HasBaseType("Models.Roles.Role");

                    b.HasDiscriminator().HasValue("DeveloppeurFront");
                });

            modelBuilder.Entity("Models.Roles.DeveloppeurMobile", b =>
                {
                    b.HasBaseType("Models.Roles.Role");

                    b.HasDiscriminator().HasValue("DeveloppeurMobile");
                });

            modelBuilder.Entity("Models.Joueur", b =>
                {
                    b.HasOne("Models.Roles.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Models.Partie", b =>
                {
                    b.HasOne("Models.Joueur", "Joueur")
                        .WithMany()
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("Models.Question", b =>
                {
                    b.HasOne("Models.Options", "OptionsProposees")
                        .WithMany()
                        .HasForeignKey("OptionsProposeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionsProposees");
                });

            modelBuilder.Entity("Models.Score", b =>
                {
                    b.HasOne("Models.Partie", null)
                        .WithMany("Scores")
                        .HasForeignKey("PartieId");
                });

            modelBuilder.Entity("Models.Partie", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
